
%% OrcaFlexInterface Sample Models
inputFiles = {'MIT-NREL_TLP\NRELOffshrBsline5MW_MIT_NREL_TLP.fst',...
              'OC3_Spar\NRELOffshrBsline5MW_OC3Hywind.fst',...
              'OC4_LC_1.3a\NRELOffshrBsline5MW_OC4DeepCwindSemi.fst',...
              'OC4_LC_1.3b\NRELOffshrBsline5MW_OC4DeepCwindSemi.fst', ...
              'OC4_LC_2.1\NRELOffshrBsline5MW_OC4DeepCwindSemi.fst',...
              'OC4_LC_2.2\NRELOffshrBsline5MW_OC4DeepCwindSemi.fst',...
              'OC4_LC_3.1\NRELOffshrBsline5MW_OC4DeepCwindSemi.fst',...
              'OC4_LC_3.2\NRELOffshrBsline5MW_OC4DeepCwindSemi.fst' };

for i=1:length(inputFiles)
    
    newDir = fileparts(inputFiles{i});    
    ConvertFAST8_12to15(inputFiles{i},newDir);
    
end

         